/*
 * Copyright 2023 Simone Baffelli
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ch.empa.openbisio

import ch.empa.openbisio.instance.InstanceDTO
import ch.empa.openbisio.instance.InstanceDeserializer
import ch.empa.openbisio.instance.InstanceMapper
import ch.empa.openbisio.instance.InstanceSerializer
import ch.ethz.sis.openbis.generic.OpenBIS
import kotlinx.cli.ArgParser
import kotlinx.cli.ArgType
import kotlinx.cli.Subcommand
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.decodeFromStream
import java.io.File


//
//
//fun sampleFetchConfig(): SampleFetchOptions {
//    val sfo = SampleFetchOptions()
//    sfo.withType().withPropertyAssignmentsUsing(assignmentFetchOptions())
//    sfo.withProperties()
//    sfo.withRegistrator()
//    return sfo
//}
//
//fun assignmentFetchOptions(): PropertyAssignmentFetchOptions {
//    val pfo = PropertyAssignmentFetchOptions().apply {
//        this.withRegistrator()
//        this.withPropertyType()
//    }
//    return pfo
//}
//
//fun collectionFetchConfig(): ExperimentFetchOptions {
//    val efo = ExperimentFetchOptions()
//    efo.withType().withPropertyAssignmentsUsing(assignmentFetchOptions())
//    efo.withProperties()
//    efo.withRegistrator()
//
//    efo.withSamplesUsing(sampleFetchConfig())
//    return efo
//}
//
//fun projectFetchConfig(): ProjectFetchOptions {
//    val pfo = ProjectFetchOptions()
//    pfo.withLeader()
//    pfo.withRegistrator()
//    pfo.withExperimentsUsing(collectionFetchConfig())
//    pfo.withSamplesUsing(sampleFetchConfig())
//    return pfo
//}
//
//fun spaceFecthConfig(): SpaceFetchOptions {
//    val sfo = SpaceFetchOptions()
//    sfo.withProjectsUsing(projectFetchConfig())
//    sfo.withSamplesUsing(sampleFetchConfig())
//    sfo.withRegistrator()
//    return sfo
//}
//
//fun sampleTypeFetchConfig(): SampleTypeFetchOptions {
//    val stfo = SampleTypeFetchOptions().apply {
//        this.withPropertyAssignmentsUsing(assignmentFetchOptions())
//    }
//    return stfo
//}
//
//


//fun dumpInstance(service: OpenBISService): Instance {
//    val spaceSearchCriteria = SpaceSearchCriteria().withAndOperator()
//    val spaceFetchConf = spaceFecthConfig()
//    val spaces = service.con.searchSpaces(service.token, spaceSearchCriteria, spaceFetchConf).objects
//    // Get property types
//    val propertyTypeSearchCriteria = PropertyTypeSearchCriteria().withAndOperator()
//    val propertyTypeFecthOptions = PropertyTypeFetchOptions()
//    propertyTypeFecthOptions.withRegistrator()
//    val props = service.con.searchPropertyTypes(service.token, propertyTypeSearchCriteria, propertyTypeFecthOptions).objects
//    // Get object types
//    val sampleTypeSearchCriteria = SampleTypeSearchCriteria().withAndOperator()
//    val sampleTypeFetchOptions = sampleTypeFetchConfig()
//    val sampleTypes = service.con.searchSampleTypes(service.token, sampleTypeSearchCriteria, sampleTypeFetchOptions).objects
//
//    val spRep = Instance(spaces, props, sampleTypes).apply(Instance::updateCodes)
//    return spRep
//}
//
//
//
enum class Mode {
    dump,
    load
}

@kotlinx.serialization.ExperimentalSerializationApi

@OptIn(kotlinx.cli.ExperimentalCli::class)
fun main(args: Array<String>) {


    val format = Json { prettyPrint = true }

    abstract class Common(name: String, description: String) : Subcommand(name, description) {
        val openbisURL by argument(ArgType.String)
        val username by argument(ArgType.String)
        val password by argument(ArgType.String)
        val ioFile by argument(ArgType.String)
    }

    class Dump : Common("dump", "Dump the instance to a file") {

        override fun execute() {
            val configFile = File(ioFile)
            val service = OpenBIS(openbisURL, 60000)
            service.login(username, password)
            val inst = InstanceDeserializer().dumpInstance(service)
            val res = format.encodeToString(InstanceDTO.serializer(), inst)
            configFile.writeText(res)
        }

    }

    class Load : Common("load", "Load the instance from a file") {

        override fun execute() {
            val configFile = File(ioFile)
            val service = OpenBIS(openbisURL, 60000)
            service.login(username, password)
            val serialiser = InstanceSerializer(service)
            val inst = Json.decodeFromStream(InstanceDTO.serializer(), configFile.inputStream())
            serialiser.persist(InstanceMapper(inst).mapToEntity())
        }
    }

    val parser = ArgParser("example")

    val summary = Dump()
    val multiple = Load()
    parser.subcommands(summary, multiple)
    parser.parse(args)

}

