/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    val kotlinVer = "1.7.20"
    id("org.jetbrains.kotlin.jvm") version kotlinVer

    alias(libs.plugins.dockerCompose)

    alias(libs.plugins.fatJar)

    //Serialisation
    id("org.jetbrains.kotlin.plugin.serialization") version kotlinVer

    // Apply the application plugin to add support for building a CLI application in Java.
    application

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
     ivy {
        url =   uri("https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/")
        patternLayout{
      
            artifact("[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]")
             ivy("[organisation]/[module]/[revision]/ivy.xml")
        }
       
    }


}



dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    // Use the Kotlin JDK 8 standard library.
    implementation(libs.kotlinStdlib)


    // Use the Kotlin test library.
    testImplementation(libs.kotlinTest)

    // Use the Kotlin JUnit integration.
    testImplementation(libs.kotlinTestJunit)

    //Openbis v3 API
    implementation(libs.openbis)

    implementation(libs.kotlinxSerialization)

    //Jackson
    implementation(libs.jacksonDatabind)

    //Email validation
    implementation(libs.jakartaMail)

    //Command line
    implementation(libs.kotlinxCLI)



}


//dockerCompose {
//    useComposeFiles.add("src/test/resources/docker-compose.yml")
//    isRequiredBy(tasks.test)
//    #'/isRequiredBy(tasks.run)
//}




ktor {
    fatJar {
        archiveFileName.set("app.jar")
    }
}



application {
    // Define the main class for the application.
    mainClass.set("openbisio.AppKt")
}
