/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin)

    alias(libs.plugins.dockerCompose)

    alias(libs.plugins.fatJar)

    //Serialisation
    alias(libs.plugins.kotlin.serialization)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    id("maven-publish")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    ivy {
        url = uri("https://sissource.ethz.ch/openbis/openbis-public/openbis-ivy/-/raw/main/")
        patternLayout {

            artifact("[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]")
            ivy("[organisation]/[module]/[revision]/ivy.xml")
        }

    }
    // Gitlab Package registry
    maven {
        val gitLabPrivateToken: String? by project
        val ciToken: String? = System.getenv("CI_JOB_TOKEN")
        url = uri("https://gitlab.empa.ch/api/v4/groups/openbis-tools/packages/maven")
        name = "Empa Gitlab"
        credentials(HttpHeaderCredentials::class) {
            name = "Private-Token"
            value = gitLabPrivateToken ?: ciToken
        }
        authentication {
            create<HttpHeaderAuthentication>("header")
        }
    }


}



dependencies {
    // Align versions of all Kotlin components
    implementation(libs.kotlin.bom)
    // Use the Kotlin JDK 8 standard library.
    implementation(libs.kotlin.stdlib)

    // Use the Kotlin test library.
    implementation(libs.kotlin.test)
    // Use the Kotlin JUnit integration.
    implementation(libs.kotlin.test.junit)

    //Openbis v3 API
    implementation(libs.openbis)

    implementation(libs.kotlinx.serialization)

    //Jackson
    implementation(libs.jackson.databind)

    //Email validation
    implementation(libs.jakarta.mail)

    //Command line
    implementation(libs.kotlinx.cli)

}






ktor {
    fatJar {
    }
}



application {
    // Define the main class for the application.
    mainClass.set("openbisio.AppKt")
}



testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnit()
            useKotlinTest()
        }
        val integrationTest by registering(JvmTestSuite::class) {
            sources {
                kotlin {
                    setSrcDirs(listOf("src/integration/kotlin/"))
                }
                resources {
                    setSrcDirs(listOf("src/integration/resources/"))
                }
            }

            dependencies {
                implementation(project())
            }
        }
    }
}


publishing {
    repositories {
        maven {
            val gitLabPrivateToken: String? by project
            val ciToken: String? = System.getenv("CI_JOB_TOKEN")
            println(gitLabPrivateToken)
            url = uri("https://gitlab.empa.ch/api/v4/projects/1644/packages/maven/")
            name = "EmpaGitlab"
            credentials(HttpHeaderCredentials::class) {
                name = "Private-Token"
                value = gitLabPrivateToken
            }
            authentication {
                create<HttpHeaderAuthentication>("header")
            }
        }
    }
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}


/* Confiugre integration tests */
val integrationTestImplementation: Configuration by configurations.getting {
    extendsFrom(configurations.testImplementation.get())
}

tasks.named("check") {
    dependsOn(testing.suites.named("integrationTest"))
}


// Only use the docker compose task for local builds. For CI/CD builds, use the services provided
// by Gitlab CI
val localBuild: Boolean = (System.getenv("LOCAL_BUILD")?.toInt() == 0) ?: true
if (localBuild) {
    dockerCompose {
        useComposeFiles.add("src/test/resources/docker-compose.yml")
        isRequiredBy(tasks.run)
        isRequiredBy(tasks.getByName("integrationTest"))
        stopContainers.set(false)
    }
}

